# Generated by Django 3.2.12 on 2023-09-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=100)),
                ('eemail', models.EmailField(max_length=254)),
                ('econtact', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'employee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('project_status', models.CharField(max_length=100)),
                ('team_lead', models.CharField(max_length=50)),
                ('project_poc', models.CharField(max_length=50)),
                ('notification_sms_recipient', models.CharField(max_length=100)),
                ('notification_email_recipient', models.CharField(max_length=100)),
                ('block_status', models.BooleanField(default=False)),
                ('inserted_by', models.CharField(max_length=250)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=250)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'project',
                'managed': True,
            },
        ),
    ]
