# Generated by Django 4.2.5 on 2023-10-15 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=100)),
                ('eemail', models.EmailField(max_length=254)),
                ('econtact', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'employee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('revised_due_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('total_deviation_days', models.IntegerField(default=0)),
                ('team_lead', models.CharField(blank=True, max_length=50)),
                ('project_poc', models.CharField(blank=True, max_length=50)),
                ('notification_sms_recipient', models.CharField(blank=True, max_length=100)),
                ('notification_email_recipient', models.CharField(blank=True, max_length=100)),
                ('block_status', models.BooleanField(default=False)),
                ('inserted_by', models.CharField(blank=True, default='admin', max_length=250)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, default='admin', max_length=250)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(blank=True, max_length=250)),
                ('project_status', models.CharField(choices=[('INITIATED', 'Initiated'), ('IN_DEV', 'In Development'), ('PAUSED', 'Paused'), ('IN_QA', 'In QA'), ('COMPLETED', 'Completed')], max_length=20)),
            ],
            options={
                'db_table': 'project',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('event_remarks', models.CharField(blank=True, max_length=250)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='employee.project')),
            ],
        ),
    ]
