# Generated by Django 4.2.5 on 2023-09-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='inserted_by',
            field=models.CharField(default='admin', max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='notification_email_recipient',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='notification_sms_recipient',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='remarks',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_by',
            field=models.CharField(default='admin', max_length=250),
        ),
    ]
