# Generated by Django 4.2.5 on 2023-09-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_project_inserted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='inserted_by',
            field=models.CharField(blank=True, default='admin', max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_by',
            field=models.CharField(blank=True, default='admin', max_length=250),
        ),
    ]
