# Generated by Django 4.2.5 on 2023-10-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_rename_xx_completion_date_project_completion_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='event',
            table='project_events',
        ),
    ]
