# Generated by Django 4.2.5 on 2023-09-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_project_inserted_by_alter_project_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_poc',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='team_lead',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
