# Generated by Django 4.2.5 on 2023-09-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_project_due_date_project_revised_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_deviation_days',
            field=models.IntegerField(default=0),
        ),
    ]
