# Generated by Django 4.2.5 on 2023-09-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_project_total_deviation_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='block_status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(default='initiated', max_length=100),
        ),
    ]
