# Generated by Django 4.2.5 on 2023-09-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_project_block_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='block_status',
            field=models.BooleanField(default=False),
        ),
    ]
