# Generated by Django 3.2.12 on 2023-09-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20230907_1032'),
        ('employee', '0009_event'),
    ]

    operations = [
    ]
