# Generated by Django 4.2.5 on 2023-09-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_remove_project_revised_due_dte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_remarks',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
