# Generated by Django 3.2.12 on 2023-09-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_event_event_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('IN_DEV', 'In Development'), ('IN_QA', 'In QA')], max_length=20),
        ),
    ]
