# Generated by Django 4.2.5 on 2023-09-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_alter_project_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('IN_DEV', 'In Development'), ('IN_QA', 'In QA'), ('COMPLETED', 'Completed')], max_length=20),
        ),
    ]
