# Generated by Django 4.2.5 on 2023-10-05 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_alter_project_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completion_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('IN_DEV', 'In Development'), ('PAUSED', 'Paused'), ('IN_QA', 'In QA'), ('COMPLETED', 'Completed')], max_length=20),
        ),
    ]
